### ISSUE TITLE
New Single Side Pools not parsing correctly

### ISSUE THREAD

**Issue by snipermonke01** [snipermonke01/gmx_python_sdk#10]

**Comment by chris-anjost** [comment]
Before the introduction of the single-sided pools for BTC and ETH, the token prices were collected from the 'BTC-USDC' and the 'WETH-USDC' pool respectively. The script still works but the prices are now the ones from the single-sided pools - which are quite different.

Is this what the issue is about?

**Comment by snipermonke01** [comment]
The scripts are rather dumb and weren't built to handle duplicate pool names, so it will collect the information for each pool and overwrite any data for the existing market.

So what you are seeing is the ETH-ETH stats overwriting the ETH-USDC stats. Fix will be deployed soon.

**Comment by snipermonke01** [comment]
Latest pull request to main fixes the parsing of duplicate pool names. Example scripts will be fully tested and fixed in upcoming change.
